name: Push to Amazon ECR
author: jwalton
description: Push a docker image to (or pull from) Amazon ECR.
inputs:
  access-key-id:
    description: Access key for IAM User.
  secret-access-key:
    description: Secret access key for IAM User.
  images:
    description: The name of the images generated. Must be same as on ECR.
  tag:
    description: The tag to use for all images.
  region:
    description: AWS Region to use.  Defaults to us-east-1.
    required: false
  direction:
    description: Whether to "push" or "pull" the image.  Defaults to "push".
    required: false
runs:
  using: node12
  main: 'main.js'
branding:
  icon: upload
  color: orange
